export default {
  projectTabs: document.querySelector("#project-tabs"),
  projectForm: document.querySelector("#project-form"),
  projectNameInput: document.querySelector("#project-name"),
  addProjectButton: document.querySelector("#add-project"),
  deleteProjectButton: document.querySelector("#delete-project"),
  todoList: document.querySelector("#todo-list"),
  todoListTitle: document.querySelector(".todo-list-header h2"),
  addTodoButton: document.querySelector(".btn-primary"),
  modalOverlay: document.querySelector(".modal-overlay"),
  modalTitle: document.querySelector(".modal h3"),
  modalForm: document.querySelector(".modal form"),
  titleInput: document.querySelector("#todo-title"),
  descriptionInput: document.querySelector("#todo-description"),
  dateInput: document.querySelector("#todo-date"),
  prioritySelect: document.querySelector("#todo-priority"),
  submitButton: document.querySelector(".modal .btn-primary"),
  cancelButton: document.querySelector(".modal .btn-ghost"),
};
